Homebrew: minor improvements/new tap for `brew cu`

diff --git a/home/.chezmoiscripts/darwin/run_once_before_01-homebrew-packages.tmpl b/home/.chezmoiscripts/darwin/run_once_before_01-homebrew-packages.tmpl
--- a/home/.chezmoiscripts/darwin/run_once_before_01-homebrew-packages.tmpl
+++ b/home/.chezmoiscripts/darwin/run_once_before_01-homebrew-packages.tmpl
@@ -20,9 +20,14 @@ install_homebrew() {
 }
 
 install_bundle() {
-  brew bundle install --file "$brewfile"
+  # Perform a system-wide upgrade first for any already-installed packages
+  if ! brew upgrade ; then
+    echo "ERROR: Failed to upgrade packages with \`brew upgrade\`!" >&2
+    exit 1
+  fi
 
-  if [[ $? -ne 0 ]] ; then
+  # Install packages based on our Brewfile
+  if ! brew bundle install --file "$brewfile" ; then
     echo "ERROR: Failed to install packages with \`brew bundle install --file \"$brewfile\"\`!" >&2
     exit 1
   fi
